name: Build/Release Desktop app

# this will help you specify where to run
on:
  push:
    branches:
      - fix/desktop-CI

env:
  REACT_APP_BLOCKNATIVE_KEY: ${{ secrets.REACT_APP_BLOCKNATIVE_KEY }}
  REACT_APP_FORTMATIC_KEY: ${{ secrets.REACT_APP_FORTMATIC_KEY }}
  REACT_APP_GOOGLE_ANALYTICS_ID_MAINNET: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID_MAINNET }}
  REACT_APP_INFURA_TOKEN: ${{ secrets.REACT_APP_INFURA_TOKEN }}
  REACT_APP_PORTIS_ID: ${{ secrets.REACT_APP_PORTIS_ID }}
  REACT_APP_GNOSIS_APPS_URL: ${{ secrets.REACT_APP_GNOSIS_APPS_URL }}
  REACT_APP_INTERCOM_ID: ${{ secrets.REACT_APP_INTERCOM_ID }}
  REACT_APP_IPFS_GATEWAY: ${{ secrets.REACT_APP_IPFS_GATEWAY }}
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Patch node gyp on windows to support Visual Studio 2019
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          yarn global add --production windows-build-tools --vs2015 --msvs_version=2015
      - name: Install node-gyp
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          yarn global add node-gyp
          yarn config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10.16
      - run: |
          mkdir .yarncache
          yarn install --frozen-lockfile --cache-folder ./.yarncache
          rm -r .yarncache
          yarn cache clean
      - name: Remove and cache clean (Windows Only)
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          rm -r -Force .yarncache
          yarn cache clean
      - name: Remove and cache clean
        if: "!startsWith(matrix.os, 'windows')"
        run: |
          rm -rf .yarncache
          yarn cache clean
